module TheTradeDeskAds
  class AdDynamicCreative < Base

    FIELDS = %w[
      AdvertiserId
      AudienceId
      AudienceName
      Description
      IncludedDataGroupIds
      ExcludedDataGroupIds
      IsAutoGenerated
    ].freeze

    class << self
    end
  end
end
